### PR TITLE
Fix some type problems detected by clang 4 on OpenBSD/adJ 6.2

### PR DESCRIPTION
**Pull request by vtamara**
In the process of helping with ONLYOFFICE/DocumentServer#221

### CODE REVIEW

**Comment by vtamara** [comment]
I notice you integrated changes of ASCOfficeOdfFileW/source/OdfFormat/odf_page_layout_state.cpp 
and 
ASCOfficeOdfFileW/source/OdfFormat/odf_drawing_context.cpp

**Comment by agolybev** [comment]
Hi @vtamara.
Yes, @ElenaSubbotina found it useful. Now I'm trying to reason her to merge your pullrequest.

**Comment by vtamara** [comment]
Problems that I can have with the coding style, feel free to correct or tell me and I will correct.

**Comment by agolybev** [comment]
Hi @vtamara,
Yes, the core module requires V8 v6.0. The version number is related with minimal version of gcc. We use the hightest version of V8 which can be compiled with gcc-4.8. It is the hightest version of gcc for Ubuntu 14.04.
Yes, you can try using another version of V8 but we can't garantee its working.

Also I have few comments for you pull request:
First, could you remove cosmetic changes:
https://github.com/ONLYOFFICE/core/pull/65/files#diff-3254ca8ef145fd640eb0d0119665c4f1
https://github.com/ONLYOFFICE/core/pull/65/files#diff-5306559b33a83b6d10722b81713bf5cc
Second, could check `m_bData` with `false` or use logical negation operator `!`
https://github.com/ONLYOFFICE/core/pull/65/files#diff-dc276deb33d9445467b7004c1c179105

**Comment by vtamara** [comment]
I'm glad that some changes were useful.

**Pull request closed without merging**
