### PR TITLE
Fix https://github.com/ONLYOFFICE/DocumentServer/issues/2692

### PR DESCRIPTION
**Pull request by anatoly-spb**
Here is the fix for https://github.com/ONLYOFFICE/DocumentServer/issues/2692 issue

### CODE REVIEW

**Comment by anatoly-spb** [comment]
I need help to understand which EBorderStyle relate to ss:LineStyle="Continuous", ss:Weight=null:
image

**Comment by anatoly-spb** [comment]
The following post can be used to test https://github.com/ONLYOFFICE/DocumentServer/issues/2692#issuecomment-2051540216

**Comment by ElenaSubbotina** [comment]
Thanks, but already in pre-release

**Comment by anatoly-spb** [comment]
> Thanks, but already in pre-release

Which branch contains these changes?

**Pull request closed without merging**
